### ISSUE TITLE
Move accounts apps from SUSI.AI server and ensure they are working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/accounts.susi.ai#1]
The accounts apps are currently at http://api.susi.ai/apps/applist/index.html. Please move the accounts from SUSI.AI server and ensure all features work in the repo.

First step is to move them here. Don't delete them on the server at this point of time.

**Comment by mariobehling** [comment]
The idea behind the accounts system is:
1. To make the front-end independent from the SUSI.AI server
2. To follow the concept of https://accounts.google.com (the concept, but not all details of it)

First step: move the apps to this repository and make them work.

**Comment by DravitLochan** [comment]
What are you trying to refer by saying "accounts"? is it http://api.susi.ai/ {which will eventually mean whole website} or http://api.susi.ai/apps/applist/index.html {the index page for apps related to accounts}?

**Comment by mariobehling** [comment]
https://fossasia.github.io/accounts.susi.ai/apps/applist/ needs to work.

**Comment by DravitLochan** [comment]
@mariobehling I think this has been achieved. Please close this issue. If something is left, please direct me towards it. 
thanks
