### ISSUE TITLE
Navigation  bar not getting populated on the  manpage

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/accounts.susi.ai#12]
**Actual Behaviour**
Navigation bar should have 3 links to it. namely : Home, API and Accounts. Right now they are getting populated by calling http://api.susi.ai/cms/topmenu.json which returns a JSON object. But the navigation  bar seems empty.

**Expected Behaviour**
Navigation bar should be populated and hence should have links. 

**LogCat for the issue**
jquery.min.js:4 Mixed Content: The page at 'https://fossasia.github.io/accounts.susi.ai/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.susi.ai/cms/topmenu.json'. This request has been blocked; the content must be served over HTTPS.

**Screenshots of the issue**
Looks like this -> ![nav_bar_absent](https://user-images.githubusercontent.com/14837478/27008743-a604c42a-4e98-11e7-8875-cbbe54c01484.png)
Should look like this -> ![orignal](https://user-images.githubusercontent.com/14837478/27008744-a63bbd2c-4e98-11e7-85a3-fc54b76f78af.png)

@Orbiter Please help!

**Comment by Orbiter** [comment]
have you debugged this, what does firebug say?

**Comment by DravitLochan** [comment]
firebug log 
>jquery.min.js:4 Mixed Content: The page at 'https://fossasia.github.io/accounts.susi.ai/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.susi.ai/cms/topmenu.json'. This request has been blocked; the content must be served over HTTPS.

I think since it is hosted on a domain provided by github, it is not allowing to make unsecure calls that is http call. I read somewhere that to make http calls on a github page, we need our own domain.

**Comment by Orbiter** [comment]
I tried this with a local copy and with api.susi.ai and both are working fine.

I asked you to open firebug, open the console and look for error messages there. Please do that now. Copy any errors reported there here.

**Comment by Orbiter** [comment]
I tested this with a local copy and on api.susi.ai and both are working fine. I don't have that issue. Which browser are you using? I tried Chrome.

**Comment by DravitLochan** [comment]
I am also using chrome. Is the bar visible to you here->  http://accounts.susi.ai ?
