### ISSUE TITLE
Add settings for each client

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/accounts.susi.ai#150]
After login, 4 settings options are visible to user (namely, android, iOS, web and CMS). Populate the settings so that user can manage them.

**Comment by anshumanv** [comment]
@DravitLochan how about we redirect the user to respective settings page like https://skills.susi.ai/settings
https://chat.susi.ai/settings
It would at least be more beneficial than the current setup.

**Comment by DravitLochan** [comment]
The actual purpose of settings in here is to redirect user here only. We want a centralized system similar to accounts.google.com. Once implemented here, they shall be removed from chat and skill cms. All that needs to be done is import the settings code from skills, android, ios and skills and place them in respective tabs. would you be able to do it?

**Comment by anshumanv** [comment]
Awesome! :smile: 
This looks interesting, I'll try to implement one at a time.

**Comment by harsh-jindal** [comment]
@DravitLochan @anshumanv IS this issue fixed?If not can i work on this? What do you mean by populate the settings?

**Comment by mariobehling** [comment]
@PrP-11 After successfully loggin in the user see a page "userhome". Please delete that route and direct the user to `/settings`

![screenshot from 2018-06-15 18-27-16](https://user-images.githubusercontent.com/1583873/41478949-db37f6c2-70c9-11e8-8de0-b90389e7c05e.png)
