### ISSUE TITLE
update to https from http

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/accounts.susi.ai#155]
**Actual Behaviour**
all calls are made to http

**Expected Behaviour**
since server is now https, update the calls  to https.

**Steps to reproduce it**
change http to https in all the AJAX calls.

**Would you like to work on the issue?**
yes

**Comment by nileshgulia1** [comment]
setting the datatype to "jsonp"
//example
``` javascript
$.ajax({
            url: "//www.site.com/resource"
            dataType: "jsonp",
            success: function(data) {
                $(".demo-card").html(data);
            }
    });
```

**Comment by anshumanv** [comment]
There are still few instances of `http`, working to migrate them.
