### ISSUE TITLE
Cannot reset account password "invalid token"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/accounts.susi.ai#156]
Trying to reset the account password from skills.susi.ai, the user gets an email "invalid token".

![screenshot from 2017-09-14 18-43-46](https://user-images.githubusercontent.com/1583873/30442472-d542d5cc-997c-11e7-8708-9d4a84283469.png)

**Comment by DravitLochan** [comment]
@mariobehling due to http to https, this is causing a bug. working on it. opened issue #155 
will send a pr to fix this.

**Comment by anshumanv** [comment]
It's perfectly functional now. :smile:
