### ISSUE TITLE
Typo in syntax in accounting.md

### ISSUE THREAD

**Issue by DipanshKhandelwal** [fossasia/accounts.susi.ai#161]
**Actual Behaviour**

https://screenshots.firefox.com/xeN4IcPD35GP80kh/github.com

**Expected Behaviour**

https://screenshots.firefox.com/d2yCBfjy4KHDfjTR/github.com

**Would you like to work on the issue?**

yes

**Comment by anshumanv** [comment]
Fixed in #160 
Close this
