### ISSUE TITLE
Close issues automatically when a PR is merged

### ISSUE THREAD

**Issue by DNS-404** [fossasia/accounts.susi.ai#185]
**Actual Behaviour**

Error in PR template. In PR template it says 
```
Fixes issue #number
```

**Expected Behaviour**

Change this to 
```
Fixes #number
```

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
#179 Similar Issue

**Comment by DNS-404** [comment]
Sorry @harsh-jindal 😅Didn't notice.
Thanks for telling me.
