### ISSUE TITLE
Improve the UI of the email and password fields in various pages

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/accounts.susi.ai#212]
**Actual Behaviour**
The UI of email and password fields is good. But can be improved.
**Expected Behaviour**
The UI of email and password can be made better.We can add icons to email and password fields.
**Screenshots of the issue**
![screen shot 2018-03-08 at 9 32 02 pm](https://user-images.githubusercontent.com/31013104/37161131-e19211ba-2317-11e8-9561-93e507f0f5a6.png)

**Would you like to work on the issue?**
YES

**Comment by PrP-11** [comment]
@harsh-jindal The UI for login and signup page is completely changes now. Therefore this issue can be closed now. Thanks.
