### ISSUE TITLE
Improve UI of login page

### ISSUE THREAD

**Issue by DNS-404** [fossasia/accounts.susi.ai#223]
**Actual Behaviour**

<img width="200" alt="screen shot 2018-03-11 at 10 41 56 am" src="https://user-images.githubusercontent.com/31174685/37250058-d5bfbea6-2519-11e8-9b2c-aa7be6c69eee.png">

**Expected Behaviour**

- No need of an "OR" there now that 'Sign Up' button is shifted with 'Login'.
- Space between "Password" and buttons below.
- Space between "Login" and "Sign Up" buttons.
- Sign Up button shouldn't be disabled in the beginning.

**Would you like to work on the issue?**

Yes

**Comment by PrP-11** [comment]
@DNS-404 I am already working on this from issue #205 about the problem with Sign Up button. Its almost complete.

**Comment by DNS-404** [comment]
@PrP-11 Issue #205 is closed

**Comment by PrP-11** [comment]
@DNS-404 It closed automatically due to another PR which was merged some hours ago.

**Comment by PrP-11** [comment]
Okay then you can proceed.
