### ISSUE TITLE
No icon for email and password text fields

### ISSUE THREAD

**Issue by PrP-11** [fossasia/accounts.susi.ai#226]
**Actual Behaviour**
Icons for email and password fields
![icons1](https://user-images.githubusercontent.com/30981465/37256208-7d97f98c-257d-11e8-8ad8-ca031ac17fae.png)

**Expected Behaviour**
Icons should be there
![icons](https://user-images.githubusercontent.com/30981465/37256215-89ee5cb2-257d-11e8-9c54-1180c1fb92c2.png)

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
Okay.. but make sure to stick to material UI only.

**Comment by Aakash-DD** [comment]
is this still open, i want to work on this

**Comment by PrP-11** [comment]
@Aakash-DD I am working on this

**Comment by SudhanvaMG** [comment]
Hey @PrP-11 i had already done this for the web chat , so i have  created a PR :)
