### ISSUE TITLE
Improve the UI (Make it like gmail)

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/accounts.susi.ai#227]
**Actual Behaviour**
The current UI is good but can be improved.
**Expected Behaviour**
The UI can made to look more like gmail.
**Screenshots of the issue**
After the changes it should look similar to this.
![screen shot 2018-03-13 at 12 21 10 am](https://user-images.githubusercontent.com/31013104/37303588-e889748c-2654-11e8-9d60-861173bfa9e5.png)

**Would you like to work on the issue?**
YES

**Comment by DravitLochan** [comment]
Sure! Go ahead!

**Comment by SudhanvaMG** [comment]
@harsh-jindal can i work on this ?

**Comment by harsh-jindal** [comment]
@SudhanvaMG I'm almost done with this, will be creating a PR shortly.

**Comment by mariobehling** [comment]
Please keep the UI aligned with skills.susi.ai
