### ISSUE TITLE
There should be a username and other details options during sign up for susi

### ISSUE THREAD

**Issue by PrP-11** [fossasia/accounts.susi.ai#239]
**Actual Behaviour**
Currently the sign up page only ask for email id and password.

**Expected Behaviour**
But it should also ask for basic details like a user name which susi can reference to while answering a query which is a general thing observed in assistants like siri and google.

**Screenshots of the issue**
![signup](https://user-images.githubusercontent.com/30981465/39829356-ce8d8532-53db-11e8-9c9b-52824e0fce18.png)

**Would you like to work on the issue?**
Yes.

**Comment by mariobehling** [comment]
This is not needed currently. A user can tell his/her name to SUSI directly.
