### ISSUE TITLE
Drop-down overlapping with the hamburger button

### ISSUE THREAD

**Issue by anshumanv** [fossasia/accounts.susi.ai#243]
**Actual Behaviour**
The drop down menu is overlapping on the hamburger button.

**Expected Behaviour**
It should appear below it.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/21009455/40545733-7df7fe1a-604a-11e8-927f-563114e51646.png)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
The dropdown needs to be the same across all components. Please follow the implementation on the CMS.
