### ISSUE TITLE
Implement new account start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/accounts.susi.ai#244]
Here is a design idea for the new account start page inspired by Twitter and Google Assistant. Please implement it.

Ensure the bottom bar is the same as on https://chat.susi.ai/overview and the top bar the same as on https://skills.susi.ai

![screenshot from 2018-05-25 23-13-05](https://user-images.githubusercontent.com/1583873/40568156-4b9c009a-6079-11e8-8828-af26562d4961.png)

**Comment by anshumanv** [comment]
Thanks for the design, working on it! :smile:

**Comment by mariobehling** [comment]
Please ensure the design works in different resolutions. Also avoid "indents" inside boxes. If a password is pre-entered the design should be without spaces and filled in "yellow" (compare to FB and Twitter).

![screenshot from 2018-06-15 18-10-28](https://user-images.githubusercontent.com/1583873/41478376-bc4386ca-70c7-11e8-9b42-9b0137267c9f.png)

**Comment by mariobehling** [comment]
It seems your solution to an issue, is to start a discussion. Of course FB and Twitter are responsive. The indent you implemented in the white right side of the start page is much bigger and this results in issues with medium sized screens. Instead of asking for each single step "what to do". Please propose and implement solutions that are close to existing services. As a GSoC student in the second term we would expect that you investigate and solve problems yourself with the help of the community and online resources.
