### ISSUE TITLE
Bug: Welcome message's position is fixed on logged In screen and show email in top bar also

### ISSUE THREAD

**Issue by PrP-11** [fossasia/accounts.susi.ai#261]
**Actual Behaviour**
![b1](https://user-images.githubusercontent.com/30981465/40905709-5d6b57a0-67fc-11e8-8807-fb7ebc9cd503.png)

**Expected Behaviour**
- It's position should not be fixed
- Email should also be shown on top bar like skills.susi and chat.susi

**Steps to reproduce it**
Decrease size on browser and scroll down.

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
Good find @PrP-11! :+1:
