### ISSUE TITLE
Autofilling credentials on login page doesn't enable login button on page load

### ISSUE THREAD

**Issue by PrP-11** [fossasia/accounts.susi.ai#265]
**Actual Behaviour**
Autofilling credentials on login page doesn't enable login button on page load

**Expected Behaviour**
The login button should be enabled on autofill

**Steps to reproduce it**
Open the login page with autofill

**Screenshots of the issue**
![b1](https://user-images.githubusercontent.com/31135861/40988950-131e2e7a-690a-11e8-83c5-9a2efb5a0bed.png)

**Would you like to work on the issue?**
Yes

**Comment by PrP-11** [comment]
@mariobehling I researched for FB and Twitter and found that FB's login page is not responsive at all. Also on twitter, They hide the login form for smaller resolutions and provide link to a simple login page. So what should we do here, either implement it as on twitter or keep it simple like current view.
![t1](https://user-images.githubusercontent.com/30981465/41507733-7ed41cec-7256-11e8-9b06-63a7b825c2a6.png)

**Comment by mariobehling** [comment]
Please ensure that the desktop page works on all standard resolutions. The button "login" should not move down.
