### ISSUE TITLE
Add user's web app settings to accounts.susi

### ISSUE THREAD

**Issue by PrP-11** [fossasia/accounts.susi.ai#266]
**Actual Behaviour**
Currently on the logged In page we see 4 icons of iOS, android, web and cms. Clicking on Web takes us to an empty page.

**Expected Behaviour**
When a user clicks on the Web icon, a page with user's web app settings should be displayed.

**Screenshots of the issue**
![a1](https://user-images.githubusercontent.com/30981465/41101274-57c07e34-6a81-11e8-83ce-1a044fc71fd6.png)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Settings not yet implemented as desired:
a) Add all options of web chat settings
b) follow same design, fonts, colors, icons as web chat

Current look:
![screenshot from 2018-06-19 11-56-07](https://user-images.githubusercontent.com/1583873/41590697-ebb34b6e-73b7-11e8-94d9-2a0ecba8d257.png)

Desired look:
![screenshot from 2018-06-19 11-34-48](https://user-images.githubusercontent.com/1583873/41590714-f5ac09c6-73b7-11e8-8af8-37082d58bc3c.png)

**Comment by mariobehling** [comment]
The settings page on the accounts system should ultimately have all options of chat, skills, Android, iOS and devices. Whatever settings any client/account of a user has should be covered here.
