### ISSUE TITLE
Improve and fix accounts top area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/accounts.susi.ai#285]
Even though the accounts page currently only has one page, it should follow the same approach as all susi.ai domains. Please change:
* Top left SUSI.AI icon needs to be linked to home directory of repo `/`
* Scrolling up should not show a white top area

![screenshot from 2018-06-22 10-42-58](https://user-images.githubusercontent.com/1583873/41767762-c8edb2ea-760a-11e8-9024-08ca6c878d94.png)

**Comment by PrP-11** [comment]
@mariobehling Working on it.
