### ISSUE TITLE
ipinfo.io is not a suitable service for an Open Source project due to very tight restrictions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/accounts.susi.ai#325]
Please take out https://ipinfo.io from the service. It is too restrictive for an Open Source project.

**Comment by akshatnitd** [comment]
Regarding this issue, the location service is actually not used in this project. The files were added during code import from chat.susi.ai. I have opened up a separate issue(https://github.com/fossasia/accounts.susi.ai/issues/329) for it. Shall I go ahead with the code refactor?
