### ISSUE TITLE
Add subroutes for different tabs of admin panel

### ISSUE THREAD

**Issue by PrP-11** [fossasia/accounts.susi.ai#345]
**Actual Behaviour**
All tabs on admin tab follows same route i.e. `/admin`

**Expected Behaviour**
Different tabs should have different subroutes. For example `/admin/users` for users tab

**Would you like to work on the issue?**
Yes

**Comment by anshumanv** [comment]
Motivation for this change?

**Comment by PrP-11** [comment]
This was discussed in the meeting and is motivated from open event.

**Comment by anshumanv** [comment]
Okay cool then.
