### ISSUE TITLE
navbar slides up

### ISSUE THREAD

**Issue by pg07codes** [fossasia/accounts.susi.ai#357]
![untitled](https://user-images.githubusercontent.com/34238240/43046863-d99d4c64-8dec-11e8-9210-f4d4ea14e9be.png)

On the page https://accounts.susi.ai/signup, on scrolling down the navbar slides up and this is left behind.
Is this intentional or i may fix it ?

**Comment by love-san** [comment]
@pg07codes Can I try to fix this issue. Thanks

**Comment by pg07codes** [comment]
sure .
