### ISSUE TITLE
Create a config for storing api end points

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/accounts.susi.ai#366]
**Actual Behaviour**

In every request which the client is making through the AJAX call, the URL is being repeated everywhere as `https://api.susi.ai`

**Expected Behaviour**

Ideally, the URL should be picked up from the config file.

**Would you like to work on the issue?**

Anyone can take it up.

**Comment by anshumanv** [comment]
Already fixed in https://github.com/fossasia/accounts.susi.ai/pull/362

**Comment by anshumanv** [comment]
@rishiraj824 thanks for this though, do you see any more instances of urls not from config file which I might've missed?
