### ISSUE TITLE
Open Admin page by default if user is an admin

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/accounts.susi.ai#369]
**Actual Behaviour**
* Currently settings open up for admin

**Expected Behaviour**
* Open Admin page by default if user is an admin

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
@akshatnitd Yes, I understand your idea, but I am worried that this will complicate things. What we need is something like admin.susi.ai. However, right now we don't have too many developers who can take care of too many components and ensure all is aligned. So, for now, let's develop the admin area here and later move it. Accounts.susi.ai should work the same way for everyone except for the admin page. Therefore closing it. Thanks.

**Comment by akshatnitd** [comment]
@mariobehling Okay, I got your point. It means, that for admin users, we will have a different website like `admin.susi.ai` in future and the `/admin` page will be removed from the accounts project. Did I understand it correctly?
