### ISSUE TITLE
Add feature for user avatar upload

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/accounts.susi.ai#399]
**Actual Behaviour**

**Expected Behaviour**

- [ ] Added feature in settings to upload avatar.
- [ ] Integrate API response of avatar
- [ ] Add feature to switch between gravatar and user uploaded avatar

Server issue: https://github.com/fossasia/susi_server/issues/1100
Ref: https://github.com/fossasia/susi_skill_cms/issues/1132
**Would you like to work on the issue?**
Yes

**Comment by meetzaveri** [comment]
@akshatnitd Hey, Is there anything you need to complete this feature. I am ready to contribute. Thanks!

**Comment by akshatnitd** [comment]
@meetzaveri The feature has already been implemented. Closing it.
There are many more open issues, please have a look at them :D
