### ISSUE TITLE
Error on npm run start

### ISSUE THREAD

**Issue by fragm3** [fossasia/accounts.susi.ai#435]
**Actual Behaviour**

After cloning, npm install, its giving error

**Expected Behaviour**

No error

**Screenshots of the issue**

<img width="882" alt="screen shot 2018-08-09 at 7 39 50 pm" src="https://user-images.githubusercontent.com/18073126/43904506-6d9a5452-9c0c-11e8-977c-af7736c968d9.png">

**Would you like to work on the issue?**

No

**Comment by anshumanv** [comment]
Hey @fragm3 :wave: 
Can you try -
```sh
sudo rm -r node_modules
npm i
npm start
```

:thinking:

**Comment by fragm3** [comment]
Not working @anshumanv

**Comment by anshumanv** [comment]
Not sure then, :thinking: maybe try recloning?

**Comment by fragm3** [comment]
Still not working :(

**Comment by pg07codes** [comment]
Any leads on this. i am also stuck. @fragm3

**Comment by akshatnitd** [comment]
@fragm3 @pg07codes Checkout this PR - https://github.com/fossasia/accounts.susi.ai/pull/466
Try to copy the changes on the PR in your package.json.
Then.
`
rm -Rf node_modules/
npm install
npm run start
`

**Comment by pg07codes** [comment]
@akshatnitd fixed my problem. Great.
