### ISSUE TITLE
The change in the avatar image doesn't reflect immediately after refresh

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/accounts.susi.ai#471]
**Actual Behaviour**
* The change in the avatar image doesn't reflect immediately after refresh. It happens as the browser caches the image and doesn't reflect the new image.

**Expected Behaviour**
* The new avatar should reflect immediately.

**Would you like to work on the issue?**
Yes

**Comment by meetzaveri** [comment]
@akshatnitd Is this bug still effective ?

**Comment by akshatnitd** [comment]
Yes, I ll send a PR for it by today.
