### ISSUE TITLE
Incorrect property name

### ISSUE THREAD

**Issue by samagragupta** [fossasia/accounts.susi.ai#493]
**Actual Behaviour**

CSS property in About class of **Login Page** is written as text-size, instead of font-size. 

**Expected Behaviour**

The property should be font-size instead of font-size.

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment]
Which property is incorrect? Link?

**Comment by samagragupta** [comment]
I have updated the issue with more details .

**Comment by samagragupta** [comment]
Done
