### ISSUE TITLE
Automatically deploy accounts to gh-pages on each PR

### ISSUE THREAD

**Issue by mariobehling** [fossasia/accounts.susi.ai#5]
Please implement automatic deployment on each PR in Github pages.

**Comment by DravitLochan** [comment]
I've deployed it here https://fossasia.github.io/accounts.susi.ai/ and synced it with master branch. This means, any pr or direct push to it will automatically modify the gh-page. If this is not what you are saying, then please guide us.

**Comment by mariobehling** [comment]
Please read the topic carefully. The goal is Automatically deploy accounts to gh-pages on each PR. This means a gh-pages branch.
