### ISSUE TITLE
Avatar Re renders onScroll everytime

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/accounts.susi.ai#501]
**Actual Behaviour**

![accounts-susi](https://user-images.githubusercontent.com/21199234/45642171-22d53a80-bad5-11e8-9250-dee29db4aa45.gif)

**Expected Behaviour**

It shouldn't be reRendered unless on refreshes page.

**Steps to reproduce it**

Go to settings of accounts.susi.ai and change tabs

**Would you like to work on the issue?**

Yes.

**Comment by tabesin** [comment]
Good observation.
