### ISSUE TITLE
Add Avatar Preview In Account Settings

### ISSUE THREAD

**Issue by fragm3** [fossasia/accounts.susi.ai#513]
**Actual Behaviour**

Only drop down to select avatar is present

**Expected Behaviour**

User should be able to preview avatar

**Steps to reproduce it**

Settings -> Account

**Would you like to work on the issue?**

Yes

**Comment by Mr-Magnificent** [comment]
![screen shot 2018-09-20 at 17 34 14](https://user-images.githubusercontent.com/23209858/45817471-8db48a80-bcfc-11e8-809a-9923a22f86c6.png)

**Comment by singhrohan62** [comment]
Hi @fragm3, its just a suggestion for you that you can autorefresh the page when user hits 'SAVE CHANGES' button or uploads avatar. Then the user will be able to see the avatar. Give it a try....
