### ISSUE TITLE
The buttons and links shift downwards when the input field of "select timezone" is selected

### ISSUE THREAD

**Issue by akshi-11** [fossasia/accounts.susi.ai#529]
**Actual Behaviour**

The right part of the page gets dislocated and the buttons and links shift downwards when the input field of select timezone is selected in the account option of settings.

**Expected Behaviour**

The page shouldn't get dislocated when the option is selected.

**Steps to reproduce it**

Go to settings/account. Try to select a timezone.

**Screenshots of the issue**

![2018-09-24 3](https://user-images.githubusercontent.com/31557923/45965551-689a8180-c046-11e8-8c89-aeb5d3d5f68c.png)

**Would you like to work on the issue?**

 Yes.

**Comment by plxity** [comment]
@akshi-11 Can I take up this issue?
