### ISSUE TITLE
Radio buttons need alignment fix

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/accounts.susi.ai#530]
**Actual Behaviour**
The radio buttons in the preferences and mic settings tab of settings page are misaligned when the screen size is decreased.

**Expected Behaviour**

The radio buttons should stay aligned even when the screen size is decreased

**Steps to reproduce it**
Go to Speech Settings and then change the screen size.

**LogCat for the issue**

**Screenshots of the issue**
![screen shot 2018-09-25 at 9 43 51 am](https://user-images.githubusercontent.com/31539812/45992953-f52a5b80-c0a9-11e8-80de-0eab5e4f0a28.png)
![screen shot 2018-09-25 at 9 43 26 am](https://user-images.githubusercontent.com/31539812/45993045-6bc75900-c0aa-11e8-8489-7952c3dfa805.png)

**Would you like to work on the issue?**
Yes

**Comment by pk1997** [comment]
Can we use media queries and fix this issue??
