### ISSUE TITLE
Phone number and country code should be together

### ISSUE THREAD

**Issue by samagragupta** [fossasia/accounts.susi.ai#531]
**Actual Behaviour**

Phone number (text field) and country code is not together when is screen is squeezed .

**Expected Behaviour**

Phone number (text field) and country code should be together

**Steps to reproduce it**

Settings -> Mobile -> Resize the window

**Screenshots of the issue**

![phone](https://user-images.githubusercontent.com/32234926/46100814-fbbeed00-c1e7-11e8-8a31-feccb95b517e.PNG)

**Comment by rossoskull** [comment]
I'd like to work on this issue
