### ISSUE TITLE
Add password strength in settings page

### ISSUE THREAD

**Issue by samagragupta** [fossasia/accounts.susi.ai#545]
**Actual Behaviour**

While entering the password in the settings page(changing password) there is no password strength indicator.

**Expected Behaviour**

While entering the password in the settings page(changing password) the password strength is shown.

**Would you like to work on the issue?**

Yes

**Comment by Kartikeya99** [comment]
Hey, I'd like to help. Is the issue still open?

**Comment by samagragupta** [comment]
@Kartikeya99 Sorry, but I have almost done the work.

**Comment by Kartikeya99** [comment]
Oh ok.
