### ISSUE TITLE
Signup form responsive design bug

### ISSUE THREAD

**Issue by rossoskull** [fossasia/accounts.susi.ai#562]
**Actual Behaviour**

The input fields aren't responsive

**Expected Behaviour**

The input fields should be responsive

**Steps to reproduce it**

Go to accounts.susi.ai -> Signup page -> resize the screen.

**Screenshots of the issue**

![screenshot from 2018-10-27 15-46-20](https://user-images.githubusercontent.com/27884543/47602669-ab61c780-d9ff-11e8-9b3e-681fa8b780f4.png)

**Would you like to work on the issue?**

Yes

**Comment by samagragupta** [comment]
An issue is already made on this : https://github.com/fossasia/accounts.susi.ai/issues/546
Also you have approved the PR
PR : https://github.com/fossasia/accounts.susi.ai/pull/550
