### ISSUE TITLE
skills button

### ISSUE THREAD

**Issue by pg07codes** [fossasia/accounts.susi.ai#583]
![image](https://user-images.githubusercontent.com/34238240/48472317-0b3bd900-e81c-11e8-8caa-95133747cc4e.png)
Problem:
- On clicking the button under Staff Picks, it just toggles it position to the left of the window.  

Possible Solution:  

-  As there is no content to scroll-by , the button should be disabled by default.

**Comment by plxity** [comment]
@pg07codes  This issue doesn't belong to this repo. Open it in susi_skill.

**Comment by pg07codes** [comment]
@plxity  alright.
