### ISSUE TITLE
No need of forgot password form

### ISSUE THREAD

**Issue by samagragupta** [fossasia/accounts.susi.ai#586]
**Actual Behaviour**

We have to write the email address in forgot password form when logged in (Change password settings)

**Expected Behaviour**

After clicking the forgot password button recovery mail should be directly sent.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

![for](https://user-images.githubusercontent.com/32234926/48668893-c1096f00-eb1d-11e8-85bf-e1d97a953292.PNG)

**Would you like to work on the issue?**

Yes

**Comment by prateek76** [comment]
@samagragupta are you still working on this??

**Comment by samagragupta** [comment]
@akshatnitd @anshumanv is this issue is valid. Should we start working on this?

**Comment by prateek76** [comment]
@samagragupta can you help me to fix this error 
![screenshot from 2018-12-12 12-15-30](https://user-images.githubusercontent.com/33982495/49851674-dc5b5780-fe07-11e8-83e6-ab43166c91bd.png)

**Comment by anshumanv** [comment]
> @akshatnitd @anshumanv is this issue is valid. Should we start working on this?

No, I think we're good without it, always better to fill the email.
