### ISSUE TITLE
Initial redux setup for handling messages ( Reducer, Actions and ActionTypes )

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/accounts.susi.ai#597]
**Actual Behaviour**

Our redux store does not handle messages as of now.

**Expected Behaviour**

Messages should be a part of our newly integrated redux store

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
It should be a part of the chat project. Please open relevant issues in that repository.
