### ISSUE TITLE
Update applist page to React

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/accounts.susi.ai#60]
**Actual Behaviour**
Current applist is on angular. 

**Expected Behaviour**
Convert it to react.

**Steps to reproduce it**

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
We don't want to re-implement the app list. We are aiming to make an accounts site for the service similar to popular services e.g. follow accounts.google.com.

Therefore closing it.
