### ISSUE TITLE
signup button disabled after filling details and captcha not showing sometimes

### ISSUE THREAD

**Issue by prateek76** [fossasia/accounts.susi.ai#615]
**Actual Behaviour**

after filling the details captcha is not shown so the signup button is disabled

**Expected Behaviour**

captcha should be visible everytime

**Steps to reproduce it**

open [https://accounts.susi.ai/signup](https://accounts.susi.ai/signup) and after reloading captcha is not visible

**Would you like to work on the issue?**

yes

**Comment by AakashMallik** [comment]
@prateek76 This problem has something to do with the captcha key, and I think is not really a bug from the app's side. This issue had arisen in chat app also and we had a little discussion on this. Hope you could continue the discussion on the chat group. Thanks.

**Comment by samagragupta** [comment]
Issue : https://github.com/fossasia/accounts.susi.ai/issues/577
PR : https://github.com/fossasia/accounts.susi.ai/pull/580

**Comment by AakashMallik** [comment]
@prateek76 Yeah, @samagragupta has already worked on this so I guess you can close this issue.
