### ISSUE TITLE
Implement the same top bar as on chat.susi.ai

### ISSUE THREAD

**Issue by mariobehling** [fossasia/accounts.susi.ai#62]
Please align the design of this app and implement the same design for the top bar as chat.susi.ai.
![screenshot from 2017-06-23 09-55-11](https://user-images.githubusercontent.com/1583873/27472021-2885b188-57fa-11e7-9de6-99860a114d2a.png)

**Comment by DravitLochan** [comment]
@mariobehling It is done. You may close this issue.
