### ISSUE TITLE
Display snackbar instead of modal for alert

### ISSUE THREAD

**Issue by AdityaSrivast** [fossasia/accounts.susi.ai#623]
**Actual Behaviour**

Currently, dialog boxes are being displayed for alert.

**Expected Behaviour**

Snackbar should be displayed instead.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/31389740/50340586-8db56800-0541-11e9-9cc7-048f6e470fcd.png)

**Would you like to work on the issue?**

Yes.

**Comment by AakashMallik** [comment]
It would be really nice if you could re use this Snack bar that i have delared. https://github.com/fossasia/accounts.susi.ai/pull/625

**Comment by AdityaSrivast** [comment]
Sure @AakashMallik I'll wait for 2 days for your PR to be merged. Otherwise, I'll proceed with the standard one.
