### ISSUE TITLE
Signup route is accessible to logged in users

### ISSUE THREAD

**Issue by plxity** [fossasia/accounts.susi.ai#637]
**Actual Behaviour**
When a logged in user visit's https://accounts.susi.ai/signup, It is accessible.

**Expected Behaviour**
Logged In user should not be allowed to visit that route.

**Steps to reproduce it**

1) Visit https://accounts.susi.ai/signup without Logging to your account.

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by AakashMallik** [comment]
@plxity You won't need the protected route in this case as you don't want to redirect the user to 404 from here. Rather redirect him to the setting route and show a snackbar saying that he is already logged in. Open to discussion.

**Comment by plxity** [comment]
@AakashMallik Yeah, I think this is the better option.
