### ISSUE TITLE
Remove Unwanted Console logs 

### ISSUE THREAD

**Issue by piyushimraw** [fossasia/accounts.susi.ai#640]
**Actual Behaviour**

unwanted console.logs when ajax request returns with error.
**Expected Behaviour**

 Console should not show any console.log for objects on Production.

**Steps to reproduce it**

 Check Console while on SignUp page https://accounts.susi.ai/signup 

**Would you like to work on the issue?**

I am working on it.

**Comment by AakashMallik** [comment]
Please fill up the issue template properly before submitting one.
