### ISSUE TITLE
Accepts whitespace in password

### ISSUE THREAD

**Issue by AvaniVerma** [fossasia/accounts.susi.ai#642]
**Actual Behaviour**
While signing up, if you put several whitespace in password, it still shows a message showing successful signup.

**Expected Behaviour**
Space should not be allowed in a password. 

**Steps to reproduce it**
Simply try to sign up with 6 or more blank space.

**Would you like to work on the issue?**
Yes

**Comment by plxity** [comment]
Any Progress?

**Comment by sakshee-19** [comment]
@AvaniVerma Are you still working on this issue?
