### ISSUE TITLE
Refactoring code in index.js

### ISSUE THREAD

**Issue by plxity** [fossasia/accounts.susi.ai#669]
**Actual Behaviour**

Components are imported from there actual file locations

**Expected Behaviour**

Instead, create a new file where all components are imported and then exported. 

`import SignUp from './components/Auth/SignUp/SignUp.react';`
`import Logout from './components/Auth/Logout.react';`
`import ResetPassword from './components/Auth/ResetPassword/ResetPassword.react';`
`import DeleteAccount from './components/Auth/DeleteAccount/DeleteAccount.react';`
`import Settings from './components/Settings/Settings.react';`
`import Admin from './components/Admin/Admin.js';`
`import Users from './components/Admin/ListUser/ListUser.js';`
`import Skills from './components/Admin/ListSkills/ListSkills.js';`
`import SystemSettings from './components/Admin/SystemSettings/SystemSettings.js';`
`import SystemLogs from './components/Admin/SystemLogs/SystemLogs.js';`
`import VerifyAccount from './components/Auth/VerifyAccount/VerifyAccount.react';`
`import Login from './components/Auth/Login/Login.react';`
`import NotFound from './components/NotFound/NotFound.react';`
`export {`
  `SignUp,`
  `Logout,`
  `ResetPassword,`
  `DeleteAccount,`
  `Settings,`
  `Admin,`
  `Users,`
  `Skills,`
  `SystemLogs,`
  `SystemSettings,`
  `VerifyAccount,`
  `Login,`
 ` NotFound,`
`};`

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by AakashMallik** [comment]
Ummm... I think you should ask the mentors before working on this. Coz we happen to be doing this for the other two repos anyway. See if they think it is necessary else your time would be wasted for nothing. @anshumanv

**Comment by plxity** [comment]
@AakashMallik Okay, I actually sent a PR  for index.js. Let's see what mentors say.

**Comment by anshumanv** [comment]
Sure this can help us with `import { ... } from './components'` 🤔 👍 

@akshatnitd you okay with this? Any negatives that you can think of?

**Comment by akshatnitd** [comment]
I do not suggest going with this approach. It will add too much dependency and overhead to update this file. We should use aliases. Read - https://github.com/facebook/create-react-app/issues/2188#issuecomment-302040874

We also think in the direction of ejecting the CRA created config and then configure the webpack aliases.

**Comment by akshatnitd** [comment]
Also, this module looks great - https://github.com/timarney/react-app-rewired. It will allow us to add aliases by overriding webpack config.
