### ISSUE TITLE
setting route redirects to some other route

### ISSUE THREAD

**Issue by AdityaSrivast** [fossasia/accounts.susi.ai#694]
**Actual Behaviour**

Currently, when not logged in and try to visit /settings route, it redirects to some other route and displays not found.

**Expected Behaviour**

It should not redirect.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/31389740/51607373-76034200-1f3a-11e9-9a4f-073eca8b82de.png)

**Would you like to work on the issue?**

Yes.

**Comment by AakashMallik** [comment]
@AdityaSrivast Ummm, why was this change needed? I mean, we are still displaying the same component. Why was the route change undesirable?

**Comment by AdityaSrivast** [comment]
@AakashMallik as developers we understand it this way. But when another user approaches the site and requests for the page, it redirects him to another page saying that the page does not exist. But the user didn't even request for it, hence giving a bad user experience.

**Comment by AakashMallik** [comment]
@AdityaSrivast well,  not sure about the bad user experience part,  coz you see, if you show a 404 at the end of the whole thing,  the user won't even bother looking at the url bar. But sure,  if you have raised an issue,  let us all have a discussion on it.  I am on my phone right now,  would u mind tagging the mentors in this PR? Thanks

**Comment by AdityaSrivast** [comment]
@AakashMallik I have already tagged the mentors on the PR.
Thanks
