### ISSUE TITLE
Login password logic not working correctly

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/accounts.susi.ai#705]
**Actual Behaviour**

The login button activates even when there is just one character in the password field. 

**Expected Behaviour**

The login button should not be activated if the number of characters in the password field is less than 6.

**Screenshots of the issue**

![screenshot-accounts susi ai-2019 01 28-18-52-01](https://user-images.githubusercontent.com/19551058/51839326-f2c56000-232e-11e9-9965-1f9a5696b03d.png)

**Would you like to work on the issue?**

Yes

**Comment by AdityaSrivast** [comment]
@AakashMallik There's already an open issue for the purpose.
https://github.com/fossasia/accounts.susi.ai/issues/578

Thanks

**Comment by AakashMallik** [comment]
@AdityaSrivast Good catch. Thanks
