### ISSUE TITLE
Console errors on accounts.susi.ai/settings page

### ISSUE THREAD

**Issue by sakshee-19** [fossasia/accounts.susi.ai#707]
**Actual Behaviour**

When we go on to accounts.susi.ai/settings page, it shows console errors.

**Expected Behaviour**

It should be fixed.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**
![screenshot from 2019-01-31 00-03-29](https://user-images.githubusercontent.com/25522394/52004428-133b1900-24ed-11e9-96ef-9dc84efab8c7.png)

**Would you like to work on the issue?**

Yes

**Comment by soulspark666** [comment]
some errors can also be found in https://accounts.susi.ai/ too
