### ISSUE TITLE
Add a cooldown to forgot password form

### ISSUE THREAD

**Issue by rossoskull** [fossasia/accounts.susi.ai#739]
**Actual Behaviour**

Currently, there is no cooldown in the forgot password form, and the user can immediately resubmit the form after submitting the form.

**Expected Behaviour**

The form should be disabled after the user has submitted the form, and should be activated if an error occurs while sending the mail or after a set time if the mail is successfully sent.

**Steps to reproduce it**

Open the forgot password modal, enter your email and submit the form.

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
I am working on this

**Comment by akshatnitd** [comment]
No need to solve this issue. Refer this for comments - https://github.com/fossasia/susi_skill_cms/pull/1959
