### ISSUE TITLE
Add Space b/w Learn More div and Log in

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/accounts.susi.ai#740]
**Actual Behaviour**
Currently there is no space b/w learn more div and log in. It looks odd in the UI.

**Expected Behaviour**
Add Space b/w the Learn More div and Log in

**Screenshots of the issue**
![Screenshot 2019-04-13 at 6 54 13 PM](https://user-images.githubusercontent.com/31013104/56080352-c2656c00-5e1d-11e9-8066-c791852ad349.png)

**Would you like to work on the issue?**
I am working on it.

**Comment by aknrg77** [comment]
i would work on this issue
