### ISSUE TITLE
Auto deployment on gh-pages.

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/accounts.susi.ai#89]
**Actual Behaviour**
on every push to master branch, gh-pages should also be updated.

**Comment by rishiraj824** [comment]
@DravitLochan Are you working on this?

**Comment by DravitLochan** [comment]
@rishiraj824 I did try this but failed to fix this. But to show progress on the main content of the project, I put it for later. Can you please work on this? should I assign this issue to you?

**Comment by rishiraj824** [comment]
Yes I can work on this. :+1:
